version: "3.8"

services:
  db:
    image: postgres:15 
    container_name: learming_managament_system
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - system

  redis:
    image: redis:7
    container_name: learming_managament_system_redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - learming_managament_system

  app:
    build: .
    container_name: learming_managament_system
    restart: always
    env_file:
      - .env
    ports:
      - "4040:3000"
    depends_on:
      - db
      - redis
    networks:
      - learming_managament_system

volumes:
  postgres_data:

networks:
  movie:
    driver: bridge
